import "../styles/globals.css";

export const metadata = {
  title: "Alani Fit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <script
          src="https://static.elfsight.com/platform/platform.js"
          data-use-service-core
          defer
        />
      </body>
    </html>
  );
}
